
#spring.datasource.url=jdbc:h2:file:/Users/paritosh/Documents/Housie/src/main/resources/housie
##spring.datasource.url=jdbc:h2:mem:housie
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.url=jdbc:mysql://bdcdff5ca6e9a9:f1453a3f@us-cdbr-iron-east-01.cleardb.net/heroku_70b3245d1cd6ec4?reconnect=true
#spring.datasource.maxActive=100
#spring.datasource.maxIdle=5
#spring.datasource.minIdle=2
#spring.datasource.initialSize=2
#spring.datasource.removeAbandoned=true

## PostgreSQL
spring.datasource.url=jdbc:postgresql://ec2-52-87-58-157.compute-1.amazonaws.com:5432/d9gsb0cl9rif4
spring.datasource.username=dottulhjnwcmbp
spring.datasource.password=c2c7c646b47850797e93cfb5fb9496355a938449cfbb51c316c16be18a9f2ae3
spring.datasource.platform=postgres
spring.jpa.show-sql=true

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=update

# These can be overridden via environment variables in hosting
custom.scheme=${CUSTOM_SCHEME:https}
server.port=${PORT:8080}
custom.host=${CUSTOM_HOST:localhost:8080}
