
#spring.datasource.url=jdbc:h2:file:/Users/paritosh/Documents/Housie/src/main/resources/housie
##spring.datasource.url=jdbc:h2:mem:housie
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://bdcdff5ca6e9a9:f1453a3f@us-cdbr-iron-east-01.cleardb.net/heroku_70b3245d1cd6ec4?reconnect=true
spring.datasource.maxActive=10
spring.datasource.maxIdle=5
spring.datasource.minIdle=2
spring.datasource.initialSize=5
spring.datasource.removeAbandoned=true

#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=update
